name: Ivan Tatić
description: "Web developer with more then 10 years of experience building exceptional websites and services."
meta_description: "Adventures in web development"

markdown: redcarpet
highlighter: pygments
logo: true
paginate: 15
paginate_path: '/blog/:num/'
baseurl: '/'
blogurl: '/blog'
# domain_name: 'http://simplified.me'
domain_name: 'https://hypernurb.herokuapp.com'
google_analytics: 'UA-267787-27'

# Details for the RSS feed generator
# url:            'http://simplified.me'
url:            'https://hypernurb.herokuapp.com'
author:         'Ivan Tatic'

exclude: [ Gemfile, Gemfile.lock, Procfile, vendor, gems]
